version: "3"

networks:
  loki:

volumes:
  loki-data: {}

services:
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./loki/local-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - ./promtail/tmp:/tmp
      - /var/log:/var/log:ro
    networks:
      - loki

  grafana:
    image: grafana/grafana:10.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3080:3000"
    networks:
      - loki
    env_file:
      - ./.grafana.env
    depends_on:
      - loki
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

