networks:
  loki:
    name: traefik
    external: true

volumes:
  loki-data: {}

services:
  loki:
    image: grafana/loki:3.2.1
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./loki/local-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    networks:
      - loki

  promtail:
    image: grafana/promtail:3.2.1
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - ./promtail/tmp:/tmp
      - /var/log:/var/log:ro
    networks:
      - loki

  grafana:
    image: grafana/grafana:11.2.3
    restart: unless-stopped
    networks:
      - grafana
    expose:
      - 3000
    volumes:
      - grafana-data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    env_file:
      - ./.grafana.env
    depends_on:
      - loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local.lan`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

