version: "3"

networks:
  gitea: {}

volumes:
  db-data: {}
  gitea-data: {}
  drone-data: {}

services:
  gitea:
    image: gitea/gitea:1.21
    container_name: gitea-server
    restart: unless-stopped
    networks:
      - gitea
    ports:
      - "3000:3000"
      - "3022:22"
    volumes:
      - gitea-data:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env/gitea.env
    depends_on:
      - db
  
  drone:
    image: drone/drone:2
    container_name: drone-ci
    restart: unless-stopped
    networks:
      - gitea
    ports:
      - 4443:443
      - 18080:80
    volumes:
      - drone-data:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env/drone.env
    depends_on:
      - gitea

  runnerd:
    image: drone/drone-runner-docker:1
    container_name: drone-runner-docker
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env/drone-runner-docker.env
    depends_on:
      - drone
  
  db:
    image: mariadb:10.4-focal
    container_name: gitea-db
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env/mariadb.env
