version: "2.4"
services:

  gitea:
    image: gitea/gitea:1.19
    container_name: gitea-server
    env_file:
      - ./app/.env/gitea.env
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./app/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "3022:22"
    depends_on:
      - db
  
  drone:
    image: drone/drone:2
    container_name: drone-ci
    restart: unless-stopped
    env_file:
      - ./drone/.env/drone.env
    networks:
      - gitea
    ports:
      - 4443:443
      - 18080:80
    volumes:
      - ./drone/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea

  runnerd:
    image: drone/drone-runner-docker:1
    container_name: drone-runner-docker
    restart: unless-stopped
    env_file:
      - ./drone/.env/drone-runner-docker.env
    networks:
      - gitea
    ports:
      - 3001:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - drone
  
  db:
    image: mariadb:10.3-focal
    container_name: gitea-db
    restart: unless-stopped
    env_file:
      - ./db/.env/mariadb.env
    networks:
      - gitea
    volumes:
      - ./db/data:/var/lib/mysql
      
networks:
  gitea:
    driver: bridge
