- type: http
  id: elastic-search-local
  name: Elastic Search
  schedule: '@every 5s'
  urls: [ "http://es.local.lan:9200/_cluster/health?pretty" ]
  check.request:
    method: GET
    headers:
      'Authorization': 'ApiKey BASE64-HASH-HERE'
  check.response:
    status: [200]

