volumes:
  ollama-data: {}
  openwebui-data: {}
  openwebui-app: {}

networks:
  ollama: {}

services:
  ollama:
    #supported GPUs
    #image: ollama/ollama:latest
    #unsupported AMD GPUs with rocm
    image: ollama/ollama:rocm
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama
    devices:
      - /dev/dri
      - /dev/kfd
    security_opt:
      - "seccomp:unconfined"
    group_add:
      - video
    environment:
      #iGPU ryzen 5600G compatible with models up to 7B
      - HSA_OVERRIDE_GFX_VERSION=9.0.0
      #- 'HCC_AMDGPU_TARGETS=gfx900'
      - HSA_ENABLE_SDMA=0

  open-webui:
    image: 'ghcr.io/open-webui/open-webui:main'
    restart: unless-stopped
    container_name: open-webui
    networks:
      - ollama
    ports:
      - 8081:8080
    environment:
        - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
        - openwebui-data:/data/docs
        - openwebui-app:/app/backend/data
