global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /logs/traefik.log

accessLog:
  format: common  # common, json, logfmt
  filePath: /logs/access.log

api:
  dashboard: true  # true by default
  insecure: true  # DEV AND TESTS ONLY

entryPoints:
  http:
    address: :80
    # Redirect to HTTPS
    # ---
    # http:
    #   redirections:
    #     entryPoint:
    #       to: https
    #       scheme: https

  https:
    address: :443

# Configure your CertificateResolver here...
# ---
# certificatesResolvers:
#   staging:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       httpChallenge:
#         entryPoint: web
#
#   production:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       httpChallenge:
#         entryPoint: web

# Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

providers:
  docker:
    exposedByDefault: true  # Default is true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true

