_format_version: "1.1"
_info:
  defaults: {}
  select_tags:
  - #SERVICE_NAME#
consumers:
- acls:
  - group: #SERVICE_NAME#
  jwt_secrets:
  - algorithm: HS256
    key: #JWT_KEY#
    secret: #JWT_SECRET#
  username: #SERVICE_NAME#
services:
- connect_timeout: 60000
  enabled: true
  host: #SERVICE_HOST#
  name: #SERVICE_NAME#
  path: #SERVICE_PATH#
  plugins:
  - config:
      allow:
      - #SERVICE_NAME#
      deny: null
      hide_groups_header: true
    enabled: true
    name: acl
    protocols:
    - grpc
    - grpcs
    - http
    - https
  - config:
      anonymous: null
      claims_to_verify: null
      cookie_names: []
      header_names:
      - authorization
      key_claim_name: iss
      maximum_expiration: 0
      run_on_preflight: true
      secret_is_base64: true
      uri_param_names:
      - jwt
    enabled: true
    name: jwt
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: #SERVICE_NAME#
    path_handling: v1
    paths:
    - #ROUTE_PATHS#
    plugins:
    - config:
        allow:
        - #SERVICE_NAME#
        deny: null
        hide_groups_header: true
      enabled: true
      name: acl
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        echo_downstream: true
        generator: uuid#counter
        header_name: Request-ID
      enabled: true
      name: correlation-id
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        anonymous: null
        claims_to_verify: null
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: true
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers:
          - Authorization
          - X-Consumer-Id
          - X-Consumer-Username
          - X-Credential-Identifier
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: null
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
