_format_version: "1.1"
_info:
  select_tags:
  - httpbin3

services:
- name: httpbin3
  url: http://httpbin.org/anything
  routes:
  - name: httpbin3
    hosts:
      - kong.local.lan
    paths:
      - /httpbin3
    protocols:
      - http
      - https
    strip_path: true
  plugins:
  - name: jwt
    config:
      secret_is_base64: false
  - name: acl
    config:
      allow:
        - httpbin3
      hide_groups_header: true
  - name: correlation-id
    config:
      generator: uuid#counter
      header_name: X-Request-Id
      echo_downstream: true
  - name: request-transformer
    config:
      remove:
        headers:
          - Authorization
          - X-Consumer-Id
          - X-Consumer-Username
          - X-Credential-Identifier
          - X-Credential-Username
      #to add upstream service Authorization header if needed
      # add:
      #   headers:
      #     - "Authorization:Bearer 123456789"

consumers:
- username: httpbin3
  jwt_secrets:
  - algorithm: HS256
    key: c7ebfc49570f2e4905e81d1e4c606eeaa75c86d4bd3177fb
    secret: c3404c44b338cf65fd540442d1783f18a30459cf33b9d388e1a1591b7f29ef4c
  acls:
  - group: httpbin3
