# just declarative sample of a httpbin.org service with common plugins, consumer and auth in the route
# make sure to change sensitive data like keys/credentials and minimal format/kong version
_format_version: "1.4"
_info:
  select_tags:
  - httpbin1

services:
- name: httpbin1
  url: http://httpbin.org/anything
  routes:
  - name: httpbin1
    hosts:
      - kong.local.lan
    paths:
      - /httpbin1
    protocols:
      - https
    strip_path: true
    plugins:
    - name: basic-auth
      config:
        hide_credentials: true
      enabled: true
    - name: acl
      config:
        allow:
          - httpbin1
        hide_groups_header: true
      enabled: true
    - name: correlation-id
      config:
        generator: uuid#counter
        header_name: X-Request-Id
        echo_downstream: true
      enabled: true
    - name: request-transformer
      config:
        remove:
          headers:
          - Authorization
          - X-Consumer-Id
          - X-Consumer-Username
          - X-Credential-Identifier
          - X-Credential-Username
        #to add upstream service Authorization header if needed
        # add:
        #   headers:
        #     - "Authorization:Bearer 123456789"
      enabled: true

consumers:
- username: httpbin1
  basicauth_credentials:
    - password: d381d244dd48807e
      username: httpbin1
  acls:
  - group: httpbin1
