# just declarative sample of a httpbin.org upstream loadbalance with passive check and active check only when passive unhealthy
_format_version: "1.4"
_info:
  select_tags:
  - upstream1

upstreams:
- name: httpbin-lb1
  algorithm: round-robin
  healthchecks:
    active:
      http_path: /anything/healthcheck
      healthy:
        http_statuses:
          - 200
        successes: 3
        interval: 0 #active check disabled
      unhealthy:
        interval: 5 #active enabled only when passive marks as unhealthy
    passive:
      type: http
      healthy:
        successes: 3
      unhealthy:
        http_failures: 5
        tcp_failures: 5
        timeouts: 5

  targets:
  - target: httpbin.org:80
    weight: 50
  - target: httpbin.konghq.com:80
    weight: 50
