FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y ansible sshpass vim nano iputils-ping

RUN userdel -r ubuntu
RUN useradd -ms /bin/bash -u 1000 ansible

WORKDIR /home/ansible
USER ansible

