version: "2.4"
services:

    agent:
      container_name: zabbix-agent2
      image: 'zabbix/zabbix-agent2:ubuntu-6.2-latest'
      restart: unless-stopped
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      networks:
        - server
      env_file:
        - ./agent/.env/zabbix-agent2.env
      depends_on:
        - server
      #Uncomment and change MEM limits
      #mem_limit: 64M
      #mem_reservation: 32M

    front:
      container_name: zabbix-front
      image: 'zabbix/zabbix-web-apache-mysql:ubuntu-6.2-latest'
      restart: unless-stopped
      networks:
        - server
        - db
      ports:
        - '80:8080'
        - '443:8443'
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - ./front/etc-zabbix/apache.conf:/etc/zabbix/apache.conf
        - ./front/etc-zabbix/apache_ssl.conf:/etc/zabbix/apache_ssl.conf
        - ./front/etc-zabbix/web/certs:/etc/zabbix/web/certs:ro
        - ./front/etc-ssl/apache2:/etc/ssl/apache2:ro
      depends_on:
        - server
      env_file:
        - ./front/.env/zabbix-front.env
      #Uncomment and change MEM limits
      #mem_limit: 512M
      #mem_reservation: 32M

    server:
      container_name: zabbix-server
      image: 'zabbix/zabbix-server-mysql:ubuntu-6.2-latest'
      restart: unless-stopped
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - ./server/usr-lib-zabbix:/usr/lib/zabbix
        - ./server/var-lib-zabbix:/var/lib/zabbix
      networks:
        - server
        - db
      depends_on:
        - db
      env_file:
        - ./server/.env/zabbix-server.env
      #Uncomment and change MEM limits
      #mem_limit: 2048M
      #mem_reservation: 512M

    db:
      container_name: zabbix-db
      image: 'mariadb:10.8-jammy'
      restart: unless-stopped
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - ./db/data:/var/lib/mysql
        - ./db/conf.d:/etc/mysql/conf.d
      networks:
        - db
      env_file:
        - ./db/.env/mariadb.env
      #Uncomment and change MEM limits
      #mem_limit: 3000M
      #mem_reservation: 512M

networks:
    server:
      driver: bridge
    db:
      driver: bridge
