name: Deploy docker stack
on:
  push:
    paths:
      - 'dnsmasq.d/**'

env:
  STACK_DIR: '/docker/pihole'

jobs:
  rsync-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Prepare Runner
        run: |
          apt update && apt-get install -y rsync

      - name: Deploy to Docker Server
        uses: easingthemes/ssh-deploy@main
        with:
          ARGS: "-rlgoDzvc -i --delete"
          SSH_PRIVATE_KEY: ${{ secrets.PI603_HOST_KEY }}
          REMOTE_USER: ${{ secrets.PI603_HOST_USER }}
          REMOTE_HOST: ${{ vars.PI603_HOST }}
          SOURCE: "dnsmasq.d"
          TARGET: "${{ env.STACK_DIR}}/"
          EXCLUDE: "logs/, .git*"
          SCRIPT_AFTER: |
            cd ${{ env.STACK_DIR}}/ || exit 2
            sudo rsync -ravgtp ./dnsmasq.d/*.conf /var/lib/docker/volumes/pihole_dnsmasq-data/_data/
            docker-compose restart


